namespace DNPAssigment1.Models
{
    public enum Job
    {
        Teacher,
        Engineer,
        GarbageCollector,
        Shepherd,
        Pilot,
        PoliceOfficer,
        Pirate,
        Fireman,
        Astronaut,
        Captain,
        Soldier,
        PizzaChef,
        Chef,
        Janitor,
        FactoryWorker,
        Chauffeur,
        Waitress,
        Ninja,
        Doctor,
        Nurse,
        Chemist,
        Caretaker,
        Gardener,
        Mascot,
        Athlete
    }
}